sudo: required
dist: trusty
language: python
python:
- '2.7'
addons:
  postgresql: "9.5"
services:
  - postgresql
env:
  global:
  - PIP_RETRIES=10
  - PIP_TIMEOUT=30
  matrix:
  #- TOXENV=checkqa
  - TOXENV=test
install:
- travis_retry pip install -U pip
- travis_retry pip install tox
- travis_retry pip freeze
before_script:
- psql -c 'create database buzzdetect_test;' -U postgres
script:
- tox
- test -d .tox/$TOXENV/log && cat .tox/$TOXENV/log/*.log || true
after_success:
- travis_retry pip install codecov
- codecov
cache:
  directories:
  - .tox/$TOXENV
  - $HOME/.cache/pip
