# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160323145530 on 2016-03-25 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('retweet_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('retweet_per_minute', models.FloatField(db_index=True, default=0)),
                ('acceleration', models.FloatField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('acceleration',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('friend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=180)),
                ('datetime', models.DateTimeField()),
                ('friends_retweets', models.PositiveIntegerField(default=0)),
                ('total_rtm', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tweets.Tweet')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Source')),
            ],
        ),
        migrations.AddField(
            model_name='retweets',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
        ),
        migrations.AlterUniqueTogether(
            name='retweets',
            unique_together=set([('datetime', 'tweet')]),
        ),
    ]
