# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='total_rtm',
            field=models.FloatField(null=True),
        ),
    ]
