# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0042_add_post_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Account')),
                ('channel_id', models.CharField(max_length=100, unique=True)),
            ],
            bases=('posts.account',),
        ),
        migrations.CreateModel(
            name='YoutubeAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
    ]
