# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models


def set_api_key(apps, schema_editor):
    YoutubeAPIKey = apps.get_model('youtubes', 'YoutubeAPIKey')
    YoutubeAccount = apps.get_model('youtubes', 'YoutubeAccount')
    key = YoutubeAPIKey.objects.first()
    if key:
        YoutubeAccount.objects.update(api_key=key.api_key)


class Migration(migrations.Migration):

    dependencies = [
        ('youtubes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeaccount',
            name='api_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(set_api_key),
        migrations.DeleteModel(
            name='YoutubeAPIKey',
        ),
    ]
