# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

TRIGGER = '''
CREATE OR REPLACE FUNCTION get_last_stat()
RETURNS trigger
AS $$
    BEGIN
        UPDATE
            posts_post
        SET
            last_stat_id = NEW.id
        WHERE
            posts_post.id = NEW.post_id;
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER update_last_stat
AFTER INSERT ON posts_stat
FOR EACH ROW EXECUTE PROCEDURE get_last_stat();
'''


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_reposts_per_follower_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_of', to='posts.Stat'),
        ),
        migrations.RunSQL(TRIGGER),
    ]
