# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

TRIGGER = '''
CREATE OR REPLACE FUNCTION update_stat_after_two_minutes()
RETURNS trigger
AS $$
    BEGIN
        UPDATE
            posts_post
        SET
            stat_after_two_minute_id = NEW.id
        WHERE
            posts_post.id = NEW.post_id
        AND
            posts_post.stat_after_two_minute_id IS NULL
        AND
            extract('epoch' from NEW.added - posts_post.datetime) >= 120
        AND
            extract('epoch' from NEW.added - posts_post.datetime) < 150;
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER update_stat_after_two_minutes
AFTER INSERT ON posts_stat
FOR EACH ROW EXECUTE PROCEDURE update_stat_after_two_minutes();
'''


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_add_post_last_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stat_after_two_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_minute_for', to='posts.Stat'),
        ),
        migrations.RunSQL(TRIGGER),
    ]
