# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models

TRIGGER = '''
CREATE OR REPLACE FUNCTION set_friends_reposts()
RETURNS trigger
AS $$
    BEGIN
        SELECT
            COUNT(posts_post.id)
        FROM
            posts_post
        LEFT JOIN
            posts_poster ON posts_post.poster_id = posts_poster.id
        WHERE
            posts_poster.friend
        AND
            posts_post.id = NEW.post_id
        INTO NEW.friends_reposts;
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER set_friends_reposts
BEFORE INSERT ON posts_stat
FOR EACH ROW EXECUTE PROCEDURE set_friends_reposts();
'''


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_add_post_stat_after_two_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='friends_reposts',
        ),
        migrations.AddField(
            model_name='stat',
            name='friends_reposts',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        # Cancel out 0004_friends_reposts
        migrations.RunSQL('drop trigger update_parent_friends_reposts on posts_post'),
        migrations.RunSQL('drop function update_parent_friends_reposts() cascade'),
        migrations.RunSQL(TRIGGER),
    ]
