# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models

TRIGGER = '''
CREATE OR REPLACE FUNCTION set_friends_reposts()
RETURNS trigger
AS $$
    BEGIN
        SELECT
            COUNT(posts_post.id)
        FROM
            posts_post
        LEFT JOIN
            posts_poster ON posts_post.poster_id = posts_poster.id
        WHERE
            posts_poster.friend
        AND
        (
            posts_post.id = NEW.post_id
            OR
            posts_post.parent_id = NEW.post_id
        )
        INTO NEW.friends_reposts;
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;
'''


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_move_friends_repost_from_post_to_stat'),
    ]

    operations = [
        migrations.RunSQL(TRIGGER),
    ]
