# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_poster_average_stat_after_two_minutes_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteraveragestat',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average_set', to='posts.Poster'),
        ),
    ]
