# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

TRIGGER = '''
CREATE OR REPLACE FUNCTION update_poster_average_after_two_minute()
RETURNS trigger
AS $$
    BEGIN
        IF
            NEW.seconds = 120
        THEN
            UPDATE
                posts_poster
            SET
                average_after_two_minute_id = NEW.id
            WHERE
                posts_poster.id = NEW.poster_id;
        END IF;
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER update_poster_average_after_two_minute
AFTER INSERT ON posts_posteraveragestat
FOR EACH ROW EXECUTE PROCEDURE update_poster_average_after_two_minute();
'''


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_poster_average_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='average_after_two_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_minute_for', to='posts.PosterAverageStat'),
        ),
        migrations.RunSQL(TRIGGER),
    ]
