# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_add_post_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='upstream_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
