# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_post_upstream_id_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upstream_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
